esphome:
  name: w-roundscreen
  friendly_name: W-RoundScreen

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: <ENC_KEY_HERE>

ota:
  - platform: esphome
    password: <OTA_PASSWORD_HERE>

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "W-Roundscreen Fallback Hotspot"
    password: <FALLBACK_HOTSPOT_PASSWORD_HERE>

captive_portal:

# Git repo examples https://esphome.io/components/packages
packages:
  # shorthand form github://username/repository/[folder/]file-path.yml[@branch-or-tag]
  #remote_package_shorthand: github://esphome/non-existant-repo/file1.yml@main

  remote_package_files:
    url: https://github.com/petrix-h/waveshare-esp32-s3-1.24-round
    files: [w-roundscreen.yaml]  # optional; if not specified, all files will be included
    ref: initial-screen-trials  # optional
    refresh: always  # optional

